var tags = [
['pacman','tag-pacman'],
['bike','tag-bike'],
['comedy','tag-comedy'],
['christmas','tag-christmas'],
['cooking','tag-cooking'],
['pac-man','tag-pac-man'],
['maze','tag-maze'],
['runner','tag-runner'],
['running','tag-running'],
['mirror','tag-mirror'],
['board games','tag-board-games'],
['race','tag-race'],
['driver','tag-driver'],
['driving','tag-driving'],
['breakout','tag-breakout'],
['guitar','tag-guitar'],
['city builder','tag-city-builder'],
['railroad','tag-railroad'],
['DJ','tag-dj'],
['train','tag-trains'],
['tower building','tag-tower-building'],
['blocks','tag-blocks'],
['pico-08','tag-pico-8'],
['katakana','tag-katakana'],
['flags quiz','tag-flags-quiz'],
['quiz','tag-quiz'],
['built','tag-built'],
['computers','tag-computers'],
['desktop','tag-desktop'],
['PC building','tag-pc-building'],
['domino','tag-domino'],
['typing','tag-typing'],
['learning japanese','tag-learn-japanese'],
['characters','tag-characters'],
['character customization','tag-character-customization'],
['mahjong','tag-mahjong'],
['2048','tag-2048'],
['printing','tag-printing'],
['anime','tag-anime'],
['xylophone','tag-xylophone'],
['driving','tag-driving'],
['piano','tag-piano'],
['math','tag-math'],
['maths','tag-maths'],
['mathimatics','tag-mathimatics'],
['words','tag-words'],
['pool','tag-pool'],
['billiard','tag-billiard'],
['bowling','tag-bowling'],
['guns','tag-guns'],
['weapons','tag-weapons'],
['minigames','tag-minigames'],
['mini','tag-mini'],
['mini games','tag-mini-games'],
['writing','tag-writing'],
['spinning top','tag-spinning-top'],
['spintop','tag-spintop'],
['spin','tag-spin'],
['rythem','tag-rythem'],
['XO','tag-xo'],
['tic-tac-toe','tag-tic-tac-toe'],
['link','tag-link'],
['tag connections','tag-connections'],
['memory','tag-memory'],
['cards','tag-cards'],
['card game','tag-card-game'],
['brain training','tag-brain-training'],
['snake','tag-snake'],
['sudoku','tag-sudoku'],
['dice','tag-dice'],
['number','tag-numbers'],
['shooting','tag-shooting'],
['FPS','tag-fps'],
['hidden object','tag-hidden-object'],
['TPS','tag-tps'],
['drumbs','tag-drumbs'],
['colour','tag-colour'],
['colors','tag-colors'],
['pinball','tag-pinball'],
['design','tag-design'],
['slots','tag-slots'],
['slot','tag-slot'],
['basket ball','tag-basketball'],
['typing tutor','tag-typing-tutor'],
['marble','tag-marble'],
['bubble','tag-bubble'],
['jigsaw','tag-jigsaw']
       ];
